package com.adl.domain

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Exports WebView cookies for a given URL into a Netscape-format cookies.txt file
 * that gallery-dl can consume. This allows the user's browser session (logins)
 * to be shared with gallery-dl.
 */
@Singleton
class CookieExporter @Inject constructor(
    private val context: Context,
) {
    /**
     * Exports cookies for the given URL to a temp file and returns its path.
     * Returns null if no cookies are available.
     */
    fun exportForUrl(url: String): File? {
        val host = Uri.parse(url).host ?: return null
        val cookieString = CookieManager.getInstance().getCookie(url)
        if (cookieString.isNullOrBlank()) return null

        val file = File(context.cacheDir, "cookies_${host.replace(".", "_")}.txt")
        val sb = StringBuilder()
        sb.appendLine("# Netscape HTTP Cookie File")
        sb.appendLine("# Generated by ADL app")

        cookieString.split(";").forEach { part ->
            val kv = part.trim().split("=", limit = 2)
            if (kv.size == 2) {
                val name = kv[0].trim()
                val value = kv[1].trim()
                // domain  includeSubDomain  path  secure  expiry  name  value
                sb.appendLine(".${host}\tTRUE\t/\tFALSE\t0\t${name}\t${value}")
            }
        }
        file.writeText(sb.toString())
        return file
    }
}
